### ISSUE TITLE
Confirm that eye tracker data collection works as documented

### ISSUE THREAD

**Issue by bastianilso** [med-material/VREyeTrackingAccuracyTest#6]
Check the that the documentation in [README.md](https://github.com/med-material/VREyeTrackingAccuracyTest/blob/master/README.md) is correct and improve it.

- [ ] Is eye tracking data collection enabled and does it log to the Documents folder as described?
- [ ] Check each variable. Are the variables logging, like the documentation describes they do? What measurement unit is it using? What are the max/min values in relation to this?
- [ ] Does the documentation describe what measurement unit the variable log to? If not, then describe that.
- [ ] Does the CSV headers describe the variable and its measurement unit adequately?
